- name: Install docker
  hosts: nginx_lb
  become: yes
  vars_files:
    - project_vars
  tasks:
    - name: Update package index
      apt: update_cache=yes

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        name: "{{ item }}"
        state: present
      loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

    - name: Add Docker's official GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Set up the stable repository
      apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' state=present

    - name: Install Docker CE
      apt: name=docker-ce state=present

    - name: start docker demon
      systemd: 
         name: docker
         state: started 

    - name: add user to docker group
      user: 
        name: ubuntu
        groups: docker 
        append: yes 

    - name: reconnect to server session
      meta: reset_connection

- name: Create nginx image from docker file
  hosts: nginx_lb
  become: yes
  vars_files:
    - project_vars
  tasks:
  - name: Install Python 3 and pip
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - python3
      - python3-pip

  - name: Install Docker SDK for Python
    pip:
      name: docker
      state: present
      extra_args: "--break-system-packages"

  - name: Copy docker & nginx.conf file to server
    copy:
      src: "{{local_nginxl7_file}}"
      dest: "/home/ubuntu/"
  
  - name: Build Docker nginx Image
    docker_image:
      name: nginxl7
      build:
        path: /home/ubuntu/nginxl7
        pull: yes
      source: build
      state: present

- name: Create nginx container from image
  hosts: nginx_lb
  become: yes
  vars: 
    container_name: nginx-lb
  tasks:
  - name: Create nginx Container
    docker_container:
      name: "{{ container_name }}"
      image: nginxl7
      ports:
          - "5000:5000"
          - "80:80"
      state: started